### PR TITLE
fix: `TextDocument.lineAt` properties

### LINKED ISSUE #564: `TextDocument.lineAt` result isn't right
Specifically looking at

https://github.com/streetsidesoftware/jest-mock-vscode/blob/f277a04dcf300d7a7ddc452f546a248e1c0f8429/src/vscode/TextDocument.ts#L53-L55

  * `isEmptyOrWhitespace: !!text.replace(/\s+/, ''),` should probably be `isEmptyOrWhitespace: !text.replace(/\s+/, ''),`
  * `firstNonWhitespaceCharacterIndex: 0` is definitely not always correct

### PR DESCRIPTION
**Pull request by harpocrates**
Fixes incorrect mocks of

  - `firstNonWhitespaceCharacterIndex`
  - `isEmptyOrWhitespace`

Fixes #564

### CODE REVIEW

File: src/vscode/TextDocument.ts [hunk 1]
```diff
@@ -46,13 +46,14 @@ export class MockTextDocument implements vscode.TextDocument {
         const lineNumber = typeof line === 'number' ? line : line.line;
         const fullLineText = this._lines[lineNumber];
         const text = fullLineText.replace(/\r?\n/, '');
+        const firstNonWhitespaceCharacterIndex = /^(\s*)/.exec(text)![1].length
```
Comment (Jason3S) [inline src/vscode/TextDocument.ts:49]: How about using `trimStart`, removing the need for a RegExp?
```suggestion
        const firstNonWhitespaceCharacterIndex = text.length - text.trimStart();
```

**Review by Jason3S — APPROVED** [review]
Thank you for the fix.

File: src/vscode/TextDocument.ts (hunk 1 above)
Comment (harpocrates) [reply src/vscode/TextDocument.ts:49]: @Jason3S happy to do that, but before I do: code there is meant to match as closely as possible the VS code impl - I wouldn't have written the check that way either, but figured if it was possible to be obviously doing the same thing as them.

Having said that, still refer with `trimStart`? If so, I'll apply.

Comment (Jason3S) [reply src/vscode/TextDocument.ts:49]: @harpocrates,

I see. Thank you.

https://github.com/microsoft/vscode/blob/56222f3441914d033791e7e7a09b99423864751b/src/vs/workbench/api/common/extHostDocumentData.ts#L284-L291
